services:
  multiservicio-rafael:
    build:
      context: .
      dockerfile: Dockerfile
    image: multiservicio-rafael:latest
    container_name: multiservicio-rafael
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
